sudo apt-get install build-essential -y
sudo apt-get install unzip -y
sudo apt-get install git -y
sudo apt-get install cmake -y
sudo apt-get install cmake-curses-gui -y
sudo apt-get install python -y
sudo apt-get install python-pip -y
sudo apt-get install libblas-dev -y
sudo apt-get install libopenblas-dev -y
sudo apt-get install libatlas-base-dev -y
sudo apt-get install liblapack-dev -y
sudo apt-get install libboost-all-dev -y
sudo apt-get install libopencv-core3.2 -y
sudo apt-get install libopencv-imgproc3.2 -y
sudo apt-get install libopencv-dev -y
sudo apt-get install libopencv-highgui3.2 -y
sudo apt-get install libopencv-highgui-dev -y
sudo apt-get install protobuf-compiler -y
sudo apt-get install libprotobuf-dev -y
sudo apt-get install libhdf5-dev -y
sudo apt-get install libjson-c-dev -y
sudo apt-get install libx11-dev -y
sudo apt-get install openjdk-8-jdk -y
sudo apt-get install wget -y
sudo apt-get install ninja-build -y